spring:
  application:
    name: online-store
  datasource:
    url: jdbc:mysql://localhost:3306/online-store?createDatabaseIfNotExist=true
    username: root
    password: tiger

stripe:
  apiUrl: https://stripe.com
  enable: true
  timeout: 3000
  supported-currency: USD,EUR,GBP

payment-gatway: paypal
